{{- if and .Values.challenges.content (not .Values.challenges.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "funwithflags.challengesSecretName" . }}
  labels:
    {{- include "funwithflags.labels" . | nindent 4 }}
type: Opaque
stringData:
  challenges.yaml: |
    {{- .Values.challenges.content | nindent 4 }}
{{- end }}
